#!/usr/bin/env python3
"""Render a session jsonl into a navigable transcript with original-line anchors (pure, read-only).

See docs/philosophy.md ("context reduction — for whom"): this is the standard reduced form
**for agents to read** — not a replacement for the raw jsonl, but a navigation layer carrying
original coordinates. Every line is tagged with `[U#]` (the Nth human turn) / `[L#]` (the
original line number); when detail is truncated, a `…[+N chars truncated]` marker is left so an
agent can use `[L#]` to jump back into the raw jsonl and recover the full content. Compression
is roughly 8–45x (depending on how much of the session is screenshots / tool output).

Two sources:
- `render_claude(path)` — Claude Code session jsonl (`~/.claude/projects/...`)
- `render_codex(path)`  — Codex rollout jsonl (`~/.codex/sessions/...`)

Both produce the **same anchored-transcript format**. The module has zero heavy dependencies
(only json/re) and is the single source of truth behind the server's `/anchored` download
endpoint.

⚠ Note when changing this: any downstream that reads the anchored transcript depends on its
**verbatim output** (truncation constants, anchor format, injection-filtering rules). Verify
byte-level diffs before and after a change.
"""
from __future__ import annotations

import json
import re


def trunc(s, n):
    if s is None:
        return ""
    s = str(s)
    return s if len(s) <= n else s[:n] + f" …[+{len(s)-n} chars truncated]"


# ───────────────────────── Self-describing header (download artifact only) ─────────────────────────

def digest_header(jsonl_path, source="claude") -> str:
    """Add a self-describing header to the download artifact: so a cold recipient with no context on
    this repo (another agent) can understand it from this .txt alone —— how to read the anchors,
    where the original file is, and where to recover the truncated detail.

    ⚠ The header is **prepended only to the /anchored download endpoint's artifact**, never into the
    render_claude/render_codex body: the offline session-review pipeline relies on its prompt template
    knowing the anchor semantics, and its "byte-for-byte identical" contract must not be broken.
    See docs/handoffs/2026-06-11-anchored-render-to-service-layer.md.
    """
    label = "Codex" if source == "codex" else "Claude Code"
    lines = [
        "# ┌─ COMPACT SESSION DIGEST ─────────────────────────────────────────",
        f"# │ Lossy, navigable digest of a {label} session. Most detail is stripped",
        "# │ to save tokens; every kept line is anchored back to the full source.",
        "# │",
        f"# │ SOURCE (full, authoritative): {jsonl_path}",
        "# │ To expand any point, open that file at the cited [L#] line.",
        "# │",
        "# │ ANCHORS",
        "# │   [L<n>]                 line <n> in the SOURCE jsonl above — go there for full content",
        "# │   [U<n>]                 the <n>-th real user turn",
        "# │   …[+N chars truncated]  N more chars exist at that [L<n>] in the source",
        "# │ MARKERS",
        "# │   ━━ [U#] … ━━  user turn   🔧 tool call   ⮑ tool output   💭 model thinking",
        "# │   [CONTEXT injected: …]   filtered boilerplate (AGENTS.md / env / permissions)",
        "# │",
        "# │ Generated by session-logbook · sources/anchored_transcript.py",
        "# └──────────────────────────────────────────────────────────────────",
    ]
    return "\n".join(lines)


# ───────────────────────── Claude Code ─────────────────────────

def _looks_b64(s):
    return isinstance(s, str) and len(s) > 2000 and re.fullmatch(r'[A-Za-z0-9+/=\s]+', s[:200] or '') is not None


def _tool_input_summary(name, inp):
    if not isinstance(inp, dict):
        return trunc(inp, 200)
    if name == 'Bash':
        return trunc(inp.get('command', ''), 300)
    if name in ('Read', 'Write', 'NotebookEdit'):
        return inp.get('file_path') or inp.get('notebook_path') or ''
    if name == 'Edit':
        return f"{inp.get('file_path','')}  old:{trunc(inp.get('old_string',''),60)!r} new:{trunc(inp.get('new_string',''),60)!r}"
    if name == 'Grep':
        return f"pattern={inp.get('pattern','')!r} path={inp.get('path','')} glob={inp.get('glob','')}"
    if name == 'Glob':
        return f"pattern={inp.get('pattern','')!r}"
    if name in ('Task', 'Agent'):
        return f"[{inp.get('subagent_type','')}] {trunc(inp.get('description',''),80)} :: {trunc(inp.get('prompt',''),200)}"
    if name == 'TodoWrite':
        todos = inp.get('todos', [])
        return "; ".join(trunc(t.get('content', ''), 50) for t in todos[:8]) if isinstance(todos, list) else trunc(inp, 150)
    if name == 'WebFetch':
        return f"{inp.get('url','')} :: {trunc(inp.get('prompt',''),100)}"
    if name == 'WebSearch':
        return trunc(inp.get('query', ''), 150)
    keys = list(inp.keys())
    return trunc("{" + ", ".join(f"{k}={trunc(inp[k],80)!r}" for k in keys[:5]) + "}", 250)


def _result_text(content):
    """tool_result content -> readable, strip images/b64."""
    if isinstance(content, str):
        if _looks_b64(content):
            return "[binary/base64 stripped]"
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if not isinstance(b, dict):
                parts.append(str(b))
                continue
            t = b.get('type')
            if t == 'text':
                tx = b.get('text', '')
                parts.append("[binary/base64 stripped]" if _looks_b64(tx) else tx)
            elif t == 'image':
                parts.append("[image]")
            else:
                parts.append(f"[{t}]")
        return "\n".join(parts)
    return str(content)


def render_claude(path) -> str:
    """Claude Code session jsonl → anchored-transcript string."""
    uturn = 0
    o_lines = []
    ln = 0
    with open(path, 'r', errors='replace') as f:
        for raw in f:
            ln += 1
            raw = raw.strip()
            if not raw:
                continue
            try:
                o = json.loads(raw)
            except Exception:
                continue
            t = o.get('type')
            ts = (o.get('timestamp') or '')[:19]
            side = ' (subagent)' if o.get('isSidechain') else ''
            if o.get('isMeta'):
                continue
            if t == 'user':
                msg = o.get('message') or {}
                content = msg.get('content')
                if isinstance(content, list) and any(isinstance(b, dict) and b.get('type') == 'tool_result' for b in content):
                    for b in content:
                        if isinstance(b, dict) and b.get('type') == 'tool_result':
                            err = ' ERROR' if b.get('is_error') else ''
                            txt = trunc(_result_text(b.get('content')), 700)
                            o_lines.append(f"[L{ln}]   ⮑ TOOL_RESULT{err}{side}: {txt}")
                else:
                    if isinstance(content, list):
                        txt = " ".join(b.get('text', '') if isinstance(b, dict) and b.get('type') == 'text' else ('[image]' if isinstance(b, dict) and b.get('type') == 'image' else '') for b in content).strip()
                    else:
                        txt = content or ''
                    uturn += 1
                    o_lines.append("")
                    o_lines.append(f"━━━━━━━━━━ [U{uturn}] [L{ln}] USER {ts}{side} ━━━━━━━━━━")
                    o_lines.append(trunc(txt, 6000))
            elif t == 'assistant':
                msg = o.get('message') or {}
                for b in (msg.get('content') or []):
                    if not isinstance(b, dict):
                        continue
                    bt = b.get('type')
                    if bt == 'text':
                        tx = (b.get('text') or '').strip()
                        if tx:
                            o_lines.append(f"[L{ln}] ASSISTANT{side}: {trunc(tx, 2500)}")
                    elif bt == 'thinking':
                        th = (b.get('thinking') or '').strip()
                        if th:
                            o_lines.append(f"[L{ln}]   💭 THINK{side}: {trunc(th, 1400)}")
                    elif bt == 'tool_use':
                        nm = b.get('name', '?')
                        o_lines.append(f"[L{ln}]   🔧 {nm}{side}: {_tool_input_summary(nm, b.get('input'))}")
            elif t == 'system':
                tx = (o.get('content') or o.get('text') or '')
                if isinstance(tx, str) and tx.strip():
                    o_lines.append(f"[L{ln}] [SYSTEM]: {trunc(tx.strip(), 300)}")
    return "\n".join(o_lines)


# ───────────────────────── Codex ─────────────────────────

_INJECT_PREFIXES = ('<user_instructions', '<environment_context', '<permissions',
                    '# agents.md', '<user_shell', '<editor', '## my environment')


def _is_injected(text):
    t = (text or '').strip().lower()
    return any(t.startswith(p) for p in _INJECT_PREFIXES)


def _msg_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        out = []
        for b in content:
            if not isinstance(b, dict):
                continue
            ty = b.get('type')
            if ty in ('input_text', 'output_text', 'text', 'summary_text'):
                out.append(b.get('text', ''))
            elif ty in ('input_image', 'image'):
                out.append('[image]')
        return "\n".join(out)
    return str(content)


def _fc_summary(name, args_raw):
    try:
        a = json.loads(args_raw) if isinstance(args_raw, str) else (args_raw or {})
    except Exception:
        return trunc(args_raw, 250)
    if not isinstance(a, dict):
        return trunc(args_raw, 250)
    if name == 'exec_command':
        return trunc(a.get('cmd', ''), 300)
    if name == 'write_stdin':
        return f"stdin: {trunc(a.get('input') or a.get('chars') or a,120)}"
    if name == 'update_plan':
        steps = a.get('plan') or []
        return "; ".join(f"[{s.get('status','')[:4]}]{trunc(s.get('step',''),40)}" for s in steps[:8]) if isinstance(steps, list) else trunc(a, 200)
    keys = list(a.keys())
    return trunc("{" + ", ".join(f"{k}={trunc(a[k],80)!r}" for k in keys[:5]) + "}", 250)


def _clean_output(out):
    if not isinstance(out, str):
        out = json.dumps(out, ensure_ascii=False)
    # Remove Codex's Chunk ID / Wall time metadata prefix lines
    lines = out.split("\n")
    lines = [l for l in lines if not l.startswith(("Chunk ID:", "Wall time:", "Total output tokens:"))]
    return "\n".join(lines).strip()


def render_codex(path) -> str:
    """Codex rollout jsonl → anchored-transcript string in the same format as Claude.

    Codex differences: reasoning is encrypted and unreadable; AGENTS.md/env/permissions are injected
    as messages and must be filtered; tools are exec_command/apply_patch/update_plan/write_stdin;
    rollback/abort are strong dissatisfaction signals.
    """
    uturn = 0
    o_lines = []
    ln = 0
    with open(path, 'r', errors='replace') as f:
        for raw in f:
            ln += 1
            raw = raw.strip()
            if not raw:
                continue
            try:
                o = json.loads(raw)
            except Exception:
                continue
            t = o.get('type')
            p = o.get('payload') or {}
            ts = (o.get('timestamp') or '')[:19]
            if t == 'session_meta':
                cwd = (p.get('cwd') or '')
                model = (p.get('model') or p.get('model_provider') or '')
                o_lines.append(f"[L{ln}] [SESSION_META] cwd={cwd} {ts}")
            elif t == 'response_item':
                pt = p.get('type')
                if pt == 'message':
                    role = p.get('role')
                    txt = _msg_text(p.get('content'))
                    if role == 'developer':
                        continue
                    if role == 'user':
                        if _is_injected(txt):
                            o_lines.append(f"[L{ln}]   [CONTEXT injected: {trunc(txt,80)}]")
                        else:
                            uturn += 1
                            o_lines.append("")
                            o_lines.append(f"━━━━━━━━━━ [U{uturn}] [L{ln}] USER {ts} ━━━━━━━━━━")
                            o_lines.append(trunc(txt, 6000))
                    elif role == 'assistant':
                        if txt.strip():
                            o_lines.append(f"[L{ln}] ASSISTANT: {trunc(txt,2500)}")
                elif pt == 'reasoning':
                    summ = _msg_text(p.get('summary'))
                    if summ.strip():
                        o_lines.append(f"[L{ln}]   💭 THINK: {trunc(summ,1400)}")
                    # encrypted reasoning with no summary is skipped (no information)
                elif pt == 'function_call':
                    nm = p.get('name', '?')
                    o_lines.append(f"[L{ln}]   🔧 {nm}: {_fc_summary(nm, p.get('arguments'))}")
                elif pt == 'function_call_output':
                    o_lines.append(f"[L{ln}]   ⮑ OUTPUT: {trunc(_clean_output(p.get('output')),700)}")
                elif pt == 'custom_tool_call':
                    nm = p.get('name', '?')
                    inp = p.get('input') or p.get('arguments')
                    o_lines.append(f"[L{ln}]   🔧 {nm}: {trunc(inp,400)}")
                elif pt == 'custom_tool_call_output':
                    o_lines.append(f"[L{ln}]   ⮑ OUTPUT: {trunc(_clean_output(p.get('output')),700)}")
                elif pt == 'web_search_call':
                    q = ''
                    act = p.get('action') or {}
                    if isinstance(act, dict):
                        q = act.get('query', '')
                    o_lines.append(f"[L{ln}]   🔧 web_search: {trunc(q,150)}")
            elif t == 'event_msg':
                et = p.get('type')
                if et == 'thread_rolled_back':
                    o_lines.append(f"[L{ln}] ⏪⏪ USER ROLLED BACK THREAD (strong dissatisfaction signal) {ts}")
                elif et == 'turn_aborted':
                    o_lines.append(f"[L{ln}] ⛔ TURN ABORTED by user (interruption signal) {ts}")
                elif et == 'context_compacted':
                    o_lines.append(f"[L{ln}] [CONTEXT COMPACTED]")
                # the remaining event_msg (token_count/agent_message/user_message/task_*) are redundant with response_item, skip
            elif t == 'compacted':
                o_lines.append(f"[L{ln}] [COMPACTED SUMMARY]")
    return "\n".join(o_lines)
